plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

packageExtensions:
  'lodash@*':
    dependencies:
      lodash: '*'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
