export const MonsterList = {
  count: 360,
  next: 'https://swarfarm.com/api/v2/monsters/?element=fire&page=2',
  previous: null,
  results: [
    {
      id: 1,
      url: 'https://swarfarm.com/api/v2/monsters/1/',
      bestiary_slug: '12302-fire-forest-keeper',
      com2us_id: 12302,
      family_id: 12300,
      name: 'Forest Keeper',
      image_filename: 'unit_icon_0010_2_1.png',
      element: 'Fire',
      archetype: 'Defense',
      base_stars: 1,
      natural_stars: 1,
      obtainable: true,
      can_awaken: false,
      awaken_level: 0,
      awaken_bonus: '',
      skills: [4],
      skill_ups_to_max: 7,
      leader_skill: null,
      homunculus_skills: [],
      base_hp: 1170,
      base_attack: 66,
      base_defense: 96,
      speed: 88,
      crit_rate: 15,
      crit_damage: 50,
      resistance: 15,
      accuracy: 0,
      raw_hp: 39,
      raw_attack: 33,
      raw_defense: 48,
      max_lvl_hp: 6420,
      max_lvl_attack: 362,
      max_lvl_defense: 527,
      awakens_from: null,
      awakens_to: null,
      awaken_cost: [],
      source: [
        {
          id: 36,
          url: 'https://swarfarm.com/api/v2/monster-sources/36/',
          name: 'Magic Shop',
          description: '',
          farmable_source: false,
        },
        {
          id: 39,
          url: 'https://swarfarm.com/api/v2/monster-sources/39/',
          name: 'Unknown Scroll or Social Summon',
          description: '',
          farmable_source: false,
        },
      ],
      fusion_food: false,
      homunculus: false,
      craft_cost: null,
      craft_materials: [],
    },
    {
      id: 2,
      url: 'https://swarfarm.com/api/v2/monsters/2/',
      bestiary_slug: '12702-fire-ghost',
      com2us_id: 12702,
      family_id: 12700,
      name: 'Ghost',
      image_filename: 'unit_icon_0010_1_4.png',
      element: 'Fire',
      archetype: 'Support',
      base_stars: 1,
      natural_stars: 1,
      obtainable: true,
      can_awaken: false,
      awaken_level: 0,
      awaken_bonus: '',
      skills: [8],
      skill_ups_to_max: 6,
      leader_skill: null,
      homunculus_skills: [],
      base_hp: 1410,
      base_attack: 94,
      base_defense: 52,
      speed: 101,
      crit_rate: 15,
      crit_damage: 50,
      resistance: 15,
      accuracy: 0,
      raw_hp: 47,
      raw_attack: 47,
      raw_defense: 26,
      max_lvl_hp: 7740,
      max_lvl_attack: 516,
      max_lvl_defense: 285,
      awakens_from: null,
      awakens_to: null,
      awaken_cost: [],
      source: [
        {
          id: 36,
          url: 'https://swarfarm.com/api/v2/monster-sources/36/',
          name: 'Magic Shop',
          description: '',
          farmable_source: false,
        },
        {
          id: 39,
          url: 'https://swarfarm.com/api/v2/monster-sources/39/',
          name: 'Unknown Scroll or Social Summon',
          description: '',
          farmable_source: false,
        },
      ],
      fusion_food: false,
      homunculus: false,
      craft_cost: null,
      craft_materials: [],
    },
    {
      id: 3,
      url: 'https://swarfarm.com/api/v2/monsters/3/',
      bestiary_slug: '13002-fire-horned-frog',
      com2us_id: 13002,
      family_id: 13000,
      name: 'Horned Frog',
      image_filename: 'unit_icon_0012_1_2.png',
      element: 'Fire',
      archetype: 'HP',
      base_stars: 1,
      natural_stars: 1,
      obtainable: true,
      can_awaken: false,
      awaken_level: 0,
      awaken_bonus: '',
      skills: [13],
      skill_ups_to_max: 5,
      leader_skill: null,
      homunculus_skills: [],
      base_hp: 1530,
      base_attack: 66,
      base_defense: 72,
      speed: 100,
      crit_rate: 15,
      crit_damage: 50,
      resistance: 15,
      accuracy: 0,
      raw_hp: 51,
      raw_attack: 33,
      raw_defense: 36,
      max_lvl_hp: 8400,
      max_lvl_attack: 362,
      max_lvl_defense: 395,
      awakens_from: null,
      awakens_to: null,
      awaken_cost: [],
      source: [
        {
          id: 39,
          url: 'https://swarfarm.com/api/v2/monster-sources/39/',
          name: 'Unknown Scroll or Social Summon',
          description: '',
          farmable_source: false,
        },
      ],
      fusion_food: false,
      homunculus: false,
      craft_cost: null,
      craft_materials: [],
    },
  ],
};
